remote_theme: pages-themes/minimal@v0.2.0
title: SfM Pipeline
description: A project for 3D reconstruction from images.
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true